export const AppEnv = {
  DATABASE_URL: process.env.DATABASE_URL!,
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  SUPABASE_KEY: process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY!,
  AUTH_GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  AUTH_GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  NEXT_AUTH_SECRET : process.env.NEXTAUTH_SECRET!
} as const;